ONOS_CREATE = 'post'
ONOS_UPDATE = 'put'
ONOS_DELETE = 'delete'

ONOS_SG = 'sg'
ONOS_SG_RULE = 'sg_rule'

ONOS_LOADBALANCER = 'loadbalancer'
ONOS_LOADBALANCERS = 'loadbalancers'
ONOS_LISTENER = 'listener'
ONOS_LISTENERS = 'listeners'
ONOS_POOL = 'pool'
ONOS_POOLS = 'pools'
ONOS_MEMBER = 'member'
ONOS_MEMBERS = 'members'
ONOS_HEALTHMONITOR = 'healthmonitor'
ONOS_HEALTHMONITORS = 'healthmonitors'
